### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by YerkoPalma** [senadores-chile/senadores#3]
# TODO

> WIP

## `typeof options === 'string'`

  - [x] `type === undefined`: Busca información por defecto de un senador, por nombre.
  - [x] `type === 'detalle'`: Busca el detalle de un senador, por nombre.
  - [x] `type === 'asistencia'`: Busca la asistencia de sala y de comisiones de un senador, por nombre.
  - [x] `type === 'asistencia.sala'`: Busca la asistencia de sala de un senador, por nombre.
  - [x] `type === 'asistencia.comisiones'`: Busca la asistencia de comisiones de un senador, por nombre.
  - [x] `type === 'viajes'`: Busca los viajes nacionales e internacionales de un senador, por nombre.
  - ~~`type === 'viajes.nacionales'`: Busca los viajes nacionales de un senador, por nombre.~~
  - [x] `type === 'viajes.internacionales'`: Busca los viajes internacionales de un senador, por nombre.
  - [x] `type === 'elecciones'`: Busca los gastos e ingresos de campaña de un senador, por nombre.
  - [x] `type === 'elecciones.ingresos'`: Busca los ingresos de campaña de un senador, por nombre.
  - [x] `type === 'elecciones.gastos'`: Busca los gastos de campaña de un senador, por nombre.
  - ~~`type === 'todos'`: Busca toda la información disponible de un senador, por nombre.~~

## `typeof options === 'number'`

  - [x] `type === undefined`: Busca información por defecto de un senador, por rut/id.
  - [x] `type === 'detalle'`: Busca el detalle de un senador, por rut/id.
  - [x] `type === 'asistencia'`: Busca la asistencia de sala y de comisiones de un senador, por rut/id.
  - [x] `type === 'asistencia.sala'`: Busca la asistencia de sala de un senador, por rut/id.
  - [x] `type === 'asistencia.comisiones'`: Busca la asistencia de comisiones de un senador, por rut/id.
  - [x] `type === 'viajes'`: Busca los viajes nacionales e internacionales de un senador, por rut/id.
  - ~~`type === 'viajes.nacionales'`: Busca los viajes nacionales de un senador, por rut/id.~~
  - [x] `type === 'viajes.internacionales'`: Busca los viajes internacionales de un senador, por rut/id.
  - [x] `type === 'elecciones'`: Busca los gastos e ingresos de campaña de un senador, por rut/id.
  - [x] `type === 'elecciones.ingresos'`: Busca los ingresos de campaña de un senador, por rut/id.
  - [x] `type === 'elecciones.gastos'`: Busca los gastos de campaña de un senador, por rut/id.
  - ~~`type === 'todos'`: Busca toda la información disponible de un senador, por rut/id.~~

## `typeof options === 'array'`

  - [x] `type === undefined`: Busca información por defecto de un grupo de senadores, por nombre o rut/id.
  - [x] `type === 'detalle'`: Busca el detalle de un grupo de senadores, por nombre o rut/id.
  - [x] `type === 'asistencia'`: Busca la asistencia de sala y de comisiones de un grupo de senadores, por nombre o rut/id.
  - [x] `type === 'asistencia.sala'`: Busca la asistencia de sala de un grupo de senadores, por nombre o rut/id.
  - [x] `type === 'asistencia.comisiones'`: Busca la asistencia de comisiones de un grupo de senadores, por nombre o rut/id.
  - [x] `type === 'viajes'`: Busca los viajes nacionales e internacionales de un grupo de senadores, por nombre o rut/id.
  - ~~`type === 'viajes.nacionales'`: Busca los viajes nacionales de un grupo de senadores, por nombre o rut/id.~~
  - [x] `type === 'viajes.internacionales'`: Busca los viajes internacionales de un grupo de senadores, por nombre o rut/id.
  - [x] `type === 'elecciones'`: Busca los gastos e ingresos de campaña de un grupo de senadores, por nombre o rut/id.
  - [x] `type === 'elecciones.ingresos'`: Busca los ingresos de campaña de un grupo de senadores, por nombre o rut/id.
  - [x] `type === 'elecciones.gastos'`: Busca los gastos de campaña de un grupo de senadores, por nombre o rut/id.
  - ~~`type === 'todos'`: Busca toda la información disponible de un grupo de senadores, por nombre o rut/id.~~

## `typeof options === 'object'`

- [x] partido<string>
- [x] region<string>
- [x] nombre<string>
- [x] rut<number>
- [x] circunscripcion<number>
- [x] telefono<string>
- [x] email<string>
- [x] cantidadSenadores<number>
- [x] asistenciaSala<string>
- [x] periodoAsistenciaSala<number | date>
- [x] periodoAsistenciaComisiones<number | date>
- [x] ingresosElecciones<string>
- [x] gastosElecciones<string>
- ~~periodoViajesNacionales<number | date>~~
- [x] periodoViajesInternacionales<number | date>

**Comment by YerkoPalma** [comment]
Add tests
